default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: ola-dev
  host: localhost
  port: 3306
  username: root
  password: 

staging:
  <<: *default
  database: <%= ENV['OLA_DB'] %>
  username: <%= ENV['OLA_DB_USER'] %>
  password: <%= ENV['OLA_DB_PASSWORD'] %>

production:
  <<: *default
  database: <%= ENV['OLA_DB'] %>
  username: <%= ENV['OLA_DB_USER'] %>
  password: <%= ENV['OLA_DB_PASSWORD'] %>